# -*- coding: utf-8 -*-
"""Copy of HTML_Column_Extractor

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YSQg3YkW11TX-J8RCDRqoqKD-nR4aEYt
"""

from bs4 import BeautifulSoup, SoupStrainer
import time

def get_column_headers(html_filepath):
  html_doc = open(html_filepath,'r')
  soup = BeautifulSoup(html_doc, 'html.parser')

  table_rows = soup.tbody.find_all('tr')
  column_headers = [tr.find_all('td')[0].contents[0] for tr in table_rows]
  return column_headers

html_doc = open("/content/drive/MyDrive/Process_Mining_SOP/Html files/YFS_ORDER_LINE.html",'r')

start_soup = time.time()
soup = BeautifulSoup(html_doc, 'lxml')
stop_soup = time.time()

print(f"Time to make soup={stop_soup-start_soup}")

print(soup.prettify())

table_rows = soup.tbody.find_all('tr')
column_headers = [tr.find_all('td')[0].contents[0] for tr in table_rows]
column_headers